curl -XPUT "172.18.114.86:9200/notconnectmm_new" -H 'Content-Type:application/json' -d'
{  
"settings":{  
"number_of_shards":1
},
"mappings":{  
"data":{  
 "date_detection":false,
 "properties":{  
	"CREGION":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CAWBNO":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DINSCANDT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CORGINLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"coutscnemp":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"CPRODCODE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CNPRODCODE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CNSUBPRDCD":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CNPACKTYPE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCURSTAT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DCURSTAT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCURSTATTIME":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCURSTATLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CSTATDESC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DPROCDT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCURSCN":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CSTATCODE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCURSCNLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DCURSCN":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCURSCNTIME":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CAREA":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCUSTCODE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCOMPGRP":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CSTR":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CPULOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CPUCUTOFF":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CDELLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"cdlvemp":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"CDELCUTOFF":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CORGHUB":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CDSTHUB":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CSERVICE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"PCPRODCODE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"PCMODE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"PCPACKTYPE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"PCORGSCRCD":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"PCDSTSCRCD":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CDPULOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CDPUCUTOFF":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CDDELLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CDDELCUTOFF":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CDORGHUB":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CDDSTHUB":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CDSERVICE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"COFFFLG":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"PCMLOCCODE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DNTWRKDT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCPU":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCPUCUTOFF":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"PCORGAREA":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"PCCUSTCODE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"PCLOADBUFF":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"PCEDT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CNFSFLG":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CROWNUM":{  
	   "type":"text"
	},
	"cscdaction":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
			}
		}
	},
	"CPROCFLAG":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DFLD":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CFLDLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DINDT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CINLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CNTWRKLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CSTATSTR":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DCPUIN":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCPUINLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DCPUOS":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCPUPOSLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DHUBIN":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CHUBINLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DHUBOS":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CHUBOSLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DNTWRKDT1":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CNTWRKLOC1":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DNTWRKDT2":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CNTWRKLOC2":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CHUBDEPT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CPURTCD":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CPURTNAME":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CPUEMPLCD":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CLOCTYPE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CSUBLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCURSCNEMP":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCURSTATEMP":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CSCDINSCAN":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CSCDOUTSCAN":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CSCDACTION":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CSCDTRANSIT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCPUINSCAN":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCPUOUTSCAN":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCPUACTION":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCPUTRANSIT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CHUBINSCAN":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CHUBOUTSCAN":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CHUBACTION":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CPRVLEFT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CREJECT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CFLD":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DCHKCUTOFF":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DOUTSCNDT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CSTATGROUP":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CUSTDATA":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"cd1":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"cd10":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd11":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd12":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd13":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd14":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd15":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd2":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd3":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd4":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd5":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd6":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd7":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd8":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"cd9":{
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
	}
	}
	},
	"CHUBNOTREACHED":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CHORGHUBSTR":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DROLLINSCANDT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CROLLINSCANLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DLOADDT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CLOADLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DDSTINDT":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CDSTINLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CNDLVSTR":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DNOTINHUB":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CNOTINHUBLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CNOTINHUB":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CDST":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CFULLROUTESTR":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DEPTDTDLV":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CINSCANSTR":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DPUDATE":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CPUTIME":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DOUTSCNDT1":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"DOUTSCNLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CRELATION":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CCRCRDREF":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CACTDELLOC":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF1":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF2":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF3":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF4":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF5":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF6":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF7":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF8":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF9":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF10":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF11":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF12":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF13":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF14":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF15":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF16":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF17":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF18":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF19":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF20":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF21":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF22":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF23":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF24":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	},
	"CF25":{  
	   "type":"text",
	   "fields":{  
		  "keyword":{  
			 "type":"keyword"
		  }
	   }
	}
	,
	"NWEIGHT":{  
	   "type":"text"
	}
	
}
}
}
}';

-----------------------------------------------------summary Index--------------------------

curl -XPUT "172.18.114.86:9200/summary_index_prod" -H 'Content-Type:application/json' -d'{  
   "settings":{  
      "number_of_shards":5
   },
   "mappings":{  
      "data":{  
         "date_detection":false,
         "properties":{ 
"CREGION":{"type": "text","fielddata": true,"fields": {"keyword": {"type": "keyword"}}},
"CNPRODCODE":{"type": "text","fielddata": true,"fields": {"keyword": {"type": "keyword"}}},
"CPRODCODE":{"type": "text","fielddata": true,"fields": {"keyword": {"type": "keyword"}}},
"CNSUBPRDCD":{"type": "text","fielddata": true,"fields": {"keyword": {"type": "keyword"}}},
"CNPACKTYPE":{"type": "text","fielddata": true,"fields": {"keyword": {"type": "keyword"}}},
"CORGINLOC":{"type": "text","fielddata": true,"fields": {"keyword": {"type": "keyword"}}},
"DPROCDT":{"type": "text","fielddata": true,"fields": {"keyword": {"type": "keyword"}}},
"CF10":{"type": "text","fielddata": true,"fields": {"keyword": {"type": "keyword"}}},
"CCOMPGRP":{"type": "text","fielddata": true,"fields": {"keyword": {"type": "keyword"}}},
"NFS":{"type": "double"},
"N015":{"type": "double"},
"N018":{"type": "double"},
"NITODAY":{"type": "double"},
"NIPRIOR":{"type": "double"},
"NIDWELL":{"type": "double"},
"NDTODAY":{"type": "double"},
"NDDWELL":{"type": "double"},
"NIDWELL24":{"type": "double"},
"ND02":{"type": "double"},
"NDPRV":{"type": "double"},
"NDCUR":{"type": "double"},
"NDTOM":{"type": "double"},
"NDLATER":{"type": "double"},
"NTBCOFF":{"type": "double"}
}
      }
   }
}';