package com.ctower.util.schema
import org.apache.spark.sql.types.{StringType,LongType}
import org.apache.spark.sql.types.TimestampType
import org.apache.spark.sql.types.StructField
import org.apache.spark.sql.types.StructType
import org.apache.spark.broadcast.Broadcast
import org.apache.spark._


object Schema {
  
  def getKafkaMessageSchema(sc:SparkContext):StructType = {
      val KafkaMessageSchema = StructType(
    List(
      StructField("BBILLCNEE", StringType),
      StructField("BCHECKLST", StringType),
      StructField("BDOXATCHD", StringType),
      StructField("BLINKED", StringType),
      StructField("BPARTIALPU", StringType),
      StructField("BPRIORITY", StringType),
      StructField("BSTAMPDART", StringType),
      StructField("CACTDELLOC", StringType),
      StructField("CADDRESSTYPE", StringType),
      StructField("CADECODE", StringType),
      StructField("CADNLCRCRDREF", StringType),
      StructField("CALTATTN", StringType),
      StructField("CATTENTION", StringType),
      StructField("CAVAILDAYS", StringType),
      StructField("CAVAILTIME", StringType),
      StructField("CAWBFEE", StringType),
      StructField("CAWBNO", StringType),
      StructField("CBATCHNO", StringType),
      StructField("CBATORG", StringType),
      StructField("CBILLCAC", StringType),
      StructField("CBILLNO", StringType),
      StructField("CBTPAREA", StringType),
      StructField("CBTPCODE", StringType),
      StructField("CCALTADR1", StringType),
      StructField("CCALTADR2", StringType),
      StructField("CCALTADR3", StringType),
      StructField("CCALTADRDT", StringType),
      StructField("CCALTFAX", StringType),
      StructField("CCALTLAT", StringType),
      StructField("CCALTLON", StringType),
      StructField("CCALTMOB", StringType),
      StructField("CCALTNAME", StringType),
      StructField("CCALTPIN", StringType),
      StructField("CCALTTEL", StringType),
      StructField("CCARDCODE", StringType),
      StructField("CCARDHOLD", StringType),
      StructField("CCARTCHG", StringType),
      StructField("CCLECTYPE", StringType),
      StructField("CCMDTYCODE", StringType),
      StructField("CCMDTYDESC", StringType),
      StructField("CCNEEADR1", StringType),
      StructField("CCNEEADR2", StringType),
      StructField("CCNEEADR3", StringType),
      StructField("CCNEEADRDT", StringType),
      StructField("CCNEECODE", StringType),
      StructField("CCNEEFADD", StringType),
      StructField("CCNEEFAX", StringType),
      StructField("CCNEEGSTNO", StringType),
      StructField("CCNEELAT", StringType),
      StructField("CCNEELON", StringType),
      StructField("CCNEEMAIL", StringType),
      StructField("CCNEEMOB", StringType),
      StructField("CCNEENAME", StringType),
      StructField("CCNEEPIN", StringType),
      StructField("CCNEETEL", StringType),
      StructField("CCNTRYCODE", StringType),
      StructField("CCODFAVOUR", StringType),
      StructField("CCODPAYBLE", StringType),
      StructField("CCONMOBMASK", StringType),
      StructField("CCRCARDNO", StringType),
      StructField("CCRCRDREF", StringType),
      StructField("CCTMNO", StringType),
      StructField("CCUSTADR1", StringType),
      StructField("CCUSTADR2", StringType),
      StructField("CCUSTADR3", StringType),
      StructField("CCUSTADRDT", StringType),
      StructField("CCUSTCODE", StringType),
      StructField("CCUSTFAX", StringType),
      StructField("CCUSTGSTNO", StringType),
      StructField("CCUSTLAT", StringType),
      StructField("CCUSTLON", StringType),
      StructField("CCUSTMOB", StringType),
      StructField("CCUSTNAME", StringType),
      StructField("CCUSTPIN", StringType),
      StructField("CCUSTPUTM", StringType),
      StructField("CCUSTTEL", StringType),
      StructField("CDHLFLAG", StringType),
      StructField("CDIMEN1", StringType),
      StructField("CDIMEN2", StringType),
      StructField("CDIMEN3", StringType),
      StructField("CDLCODE", StringType),
      StructField("CDOCNO", StringType),
      StructField("CDSTAREA", StringType),
      StructField("CDSTSCRCD", StringType),
      StructField("CEMAILID", StringType),
      StructField("CEXCHAWB", StringType),
      StructField("CFLFM", StringType),
      StructField("CFLIGHTNO", StringType),
      StructField("CFOCCODE", StringType),
      StructField("CFODCODFLG", StringType),
      StructField("CFOVTYPE", StringType),
      StructField("CFRDAWBNO", StringType),
      StructField("CGSACODE", StringType),
      StructField("CGSTNO", StringType),
      StructField("CILLOC", StringType),
      StructField("CINVNO", StringType),
      StructField("CISDDN", StringType),
      StructField("CKGPOUND", StringType),
      StructField("CLOCCODE", StringType),
      StructField("CMANIFSTNO", StringType),
      StructField("CMAWBNO", StringType),
      StructField("CMISCCHG1", StringType),
      StructField("CMISCCHG2", StringType),
      StructField("CMLOCCODE", StringType),
      StructField("CMODE", StringType),
      StructField("CMRKSNOS1", StringType),
      StructField("CMRKSNOS2", StringType),
      StructField("CMRKSNOS3", StringType),
      StructField("COCTRCPTNO", StringType),
      StructField("CODA", StringType),
      StructField("COFFCLTIME", StringType),
      StructField("CORGAREA", StringType),
      StructField("CORGSCRCD", StringType),
      StructField("CPACKTYPE", StringType),
      StructField("CPAYTYPE", StringType),
      StructField("CPREFTM", StringType),
      StructField("CPRODCODE", StringType),
      StructField("CPRODDESC", StringType),
      StructField("CPRODTYPE", StringType),
      StructField("CPSCODE", StringType),
      StructField("CPUEMPLCD", StringType),
      StructField("CPUMODE", StringType),
      StructField("CPUTIME", StringType),
      StructField("CPUTYPE", StringType),
      StructField("CPUWI", StringType),
      StructField("CREFNO2", StringType),
      StructField("CREFNO3", StringType),
      StructField("CREGCUSTADR1", StringType),
      StructField("CREGCUSTADR2", StringType),
      StructField("CREGCUSTADR3", StringType),
      StructField("CREGCUSTADRDT", StringType),
      StructField("CREGCUSTLAT", StringType),
      StructField("CREGCUSTLON", StringType),
      StructField("CREGCUSTNAME", StringType),
      StructField("CREGCUSTPIN", StringType),
      StructField("CREGCUSTTEL", StringType),
      StructField("CREGTCHG", StringType),
      StructField("CREVPU", StringType),
      StructField("CRFDCOMPNM", StringType),
      StructField("CRTOADR1", StringType),
      StructField("CRTOADR2", StringType),
      StructField("CRTOADR3", StringType),
      StructField("CRTOADRDT", StringType),
      StructField("CRTOCONTNM", StringType),
      StructField("CRTOIMDTLY", StringType),
      StructField("CRTOLAT", StringType),
      StructField("CRTOLON", StringType),
      StructField("CRTOMOB", StringType),
      StructField("CRTOPIN", StringType),
      StructField("CRTOTEL", StringType),
      StructField("CSENDER", StringType),
      StructField("CSPLINST", StringType),
      StructField("CSTATCHG", StringType),
      StructField("CSTATECODE", StringType),
      StructField("CSUBCODE", StringType),
      StructField("CTRNCODE", StringType),
      StructField("DBATCHDT", StringType),
      StructField("DCUSTEDD", StringType),
      StructField("DCUSTPUDT", StringType),
      StructField("DDOCDATE", StringType),
      StructField("DDWNLDDATE", StringType),
      StructField("DEPTDTDLV", StringType),
      StructField("DFLIGHTDT", StringType),
      StructField("DINVDATE", StringType),
      StructField("DPUDATE", StringType),
      StructField("DSHIPDATE", StringType),
      StructField("DUPLDATE", StringType),
      StructField("DVALIDUPTO", StringType),
      StructField("NACTWGT", StringType),
      StructField("NADDISRCHG", StringType),
      StructField("NADDOSRCHG", StringType),
      StructField("NAMOUNT", StringType),
      StructField("NAMT", StringType),
      StructField("NASSDVALUE", StringType),
      StructField("NAWBFEE", StringType),
      StructField("NCARTCHG", StringType),
      StructField("NCDUTYPC", StringType),
      StructField("NCHGCOLCT", StringType),
      StructField("NCHRGWT", StringType),
      StructField("NCOLAMT", StringType),
      StructField("NCOMVAL", StringType),
      StructField("NCSHMEMNO", StringType),
      StructField("NDCCHRG", StringType),
      StructField("NDCLRDVAL", StringType),
      StructField("NDEFERREDDELIVERYDAYS", StringType),
      StructField("NDIMB", StringType),
      StructField("NDIMH", StringType),
      StructField("NDIML", StringType),
      StructField("NDIWT", StringType),
      StructField("NDOCCHRG", StringType),
      StructField("NDODAMT", StringType),
      StructField("NFODCHRG", StringType),
      StructField("NFREIGHT", StringType),
      StructField("NFSAMT", StringType),
      StructField("NITEMCNT", StringType),
      StructField("NMISCCHG1", StringType),
      StructField("NMISCCHG2", StringType),
      StructField("NOCTROI", StringType),
      StructField("NODACHRG", StringType),
      StructField("NOTHCHRGS", StringType),
      StructField("NPAYCASH", StringType),
      StructField("NPCS", StringType),
      StructField("NPUTMSLOT", StringType),
      StructField("NREGTCHG", StringType),
      StructField("NRISKHCHGS", StringType),
      StructField("NSLABWGT", StringType),
      StructField("NSTATCHG", StringType),
      StructField("NTOKENNO", StringType),
      StructField("NVALCHGS", StringType),
      StructField("NWEIGHT", StringType)))

  val schema = (new StructType).add("after", KafkaMessageSchema).add("current_ts", StringType)
    .add("op_ts", StringType)
    .add("op_type", StringType)
    .add("pos", StringType)
    .add("table", StringType)

  val KafkaMessageSchema_broadcast = schema
  //val KafkaMessageSchema_broadcast = sc.broadcast(schema)
  return KafkaMessageSchema_broadcast
  
  }
  
  def getShipcltSchema(sc:SparkContext): StructType = {
    val shipcltSchema = StructType(
    List(
      StructField("BBILLCNEE", StringType, true),
      StructField("BCHECKLST", StringType, true),
      StructField("BDOXATCHD", StringType, true),
      StructField("BLINKED", StringType, true),
      StructField("BPARTIALPU", StringType, true),
      StructField("BPRIORITY", StringType, true),
      StructField("BSTAMPDART", StringType, true),
      StructField("CACTDELLOC", StringType, true),
      StructField("CADDRESSTYPE", StringType, true),
      StructField("CADECODE", StringType, true),
      StructField("CADNLCRCRDREF", StringType, true),
      StructField("CALTATTN", StringType, true),
      StructField("CATTENTION", StringType, true),
      StructField("CAVAILDAYS", StringType, true),
      StructField("CAVAILTIME", StringType, true),
      StructField("CAWBFEE", StringType, true),
      StructField("CAWBNO", StringType, true),
      StructField("CBATCHNO", StringType, true),
      StructField("CBATORG", StringType, true),
      StructField("CBILLCAC", StringType, true),
      StructField("CBILLNO", StringType, true),
      StructField("CBTPAREA", StringType, true),
      StructField("CBTPCODE", StringType, true),
      StructField("CCALTADR1", StringType, true),
      StructField("CCALTADR2", StringType, true),
      StructField("CCALTADR3", StringType, true),
      StructField("CCALTADRDT", StringType, true),
      StructField("CCALTFAX", StringType, true),
      StructField("CCALTLAT", StringType, true),
      StructField("CCALTLON", StringType, true),
      StructField("CCALTMOB", StringType, true),
      StructField("CCALTNAME", StringType, true),
      StructField("CCALTPIN", StringType, true),
      StructField("CCALTTEL", StringType, true),
      StructField("CCARDCODE", StringType, true),
      StructField("CCARDHOLD", StringType, true),
      StructField("CCARTCHG", StringType, true),
      StructField("CCLECTYPE", StringType, true),
      StructField("CCMDTYCODE", StringType, true),
      StructField("CCMDTYDESC", StringType, true),
      StructField("CCNEEADR1", StringType, true),
      StructField("CCNEEADR2", StringType, true),
      StructField("CCNEEADR3", StringType, true),
      StructField("CCNEEADRDT", StringType, true),
      StructField("CCNEECODE", StringType, true),
      StructField("CCNEEFADD", StringType, true),
      StructField("CCNEEFAX", StringType, true),
      StructField("CCNEEGSTNO", StringType, true),
      StructField("CCNEELAT", StringType, true),
      StructField("CCNEELON", StringType, true),
      StructField("CCNEEMAIL", StringType, true),
      StructField("CCNEEMOB", StringType, true),
      StructField("CCNEENAME", StringType, true),
      StructField("CCNEEPIN", StringType, true),
      StructField("CCNEETEL", StringType, true),
      StructField("CCNTRYCODE", StringType, true),
      StructField("CCODFAVOUR", StringType, true),
      StructField("CCODPAYBLE", StringType, true),
      StructField("CCONMOBMASK", StringType, true),
      StructField("CCRCARDNO", StringType, true),
      StructField("CCRCRDREF", StringType, true),
      StructField("CCTMNO", StringType, true),
      StructField("CCUSTADR1", StringType, true),
      StructField("CCUSTADR2", StringType, true),
      StructField("CCUSTADR3", StringType, true),
      StructField("CCUSTADRDT", StringType, true),
      StructField("CCUSTCODE", StringType, true),
      StructField("CCUSTFAX", StringType, true),
      StructField("CCUSTGSTNO", StringType, true),
      StructField("CCUSTLAT", StringType, true),
      StructField("CCUSTLON", StringType, true),
      StructField("CCUSTMOB", StringType, true),
      StructField("CCUSTNAME", StringType, true),
      StructField("CCUSTPIN", StringType, true),
      StructField("CCUSTPUTM", StringType, true),
      StructField("CCUSTTEL", StringType, true),
      StructField("CDHLFLAG", StringType, true),
      StructField("CDIMEN1", StringType, true),
      StructField("CDIMEN2", StringType, true),
      StructField("CDIMEN3", StringType, true),
      StructField("CDLCODE", StringType, true),
      StructField("CDOCNO", StringType, true),
      StructField("CDSTAREA", StringType, true),
      StructField("CDSTSCRCD", StringType, true),
      StructField("CEMAILID", StringType, true),
      StructField("CEXCHAWB", StringType, true),
      StructField("CFLFM", StringType, true),
      StructField("CFLIGHTNO", StringType, true),
      StructField("CFOCCODE", StringType, true),
      StructField("CFODCODFLG", StringType, true),
      StructField("CFOVTYPE", StringType, true),
      StructField("CFRDAWBNO", StringType, true),
      StructField("CGSACODE", StringType, true),
      StructField("CGSTNO", StringType, true),
      StructField("CILLOC", StringType, true),
      StructField("CINVNO", StringType, true),
      StructField("CISDDN", StringType, true),
      StructField("CKGPOUND", StringType, true),
      StructField("CLOCCODE", StringType, true),
      StructField("CMANIFSTNO", StringType, true),
      StructField("CMAWBNO", StringType, true),
      StructField("CMISCCHG1", StringType, true),
      StructField("CMISCCHG2", StringType, true),
      StructField("CMLOCCODE", StringType, true),
      StructField("CMODE", StringType, true),
      StructField("CMRKSNOS1", StringType, true),
      StructField("CMRKSNOS2", StringType, true),
      StructField("CMRKSNOS3", StringType, true),
      StructField("COCTRCPTNO", StringType, true),
      StructField("CODA", StringType, true),
      StructField("COFFCLTIME", StringType, true),
      StructField("CORGAREA", StringType, true),
      StructField("CORGSCRCD", StringType, true),
      StructField("CPACKTYPE", StringType, true),
      StructField("CPAYTYPE", StringType, true),
      StructField("CPREFTM", StringType, true),
      StructField("CPRODCODE", StringType, true),
      StructField("CPRODDESC", StringType, true),
      StructField("CPRODTYPE", StringType, true),
      StructField("CPSCODE", StringType, true),
      StructField("CPUEMPLCD", StringType, true),
      StructField("CPUMODE", StringType, true),
      StructField("CPUTIME", StringType, true),
      StructField("CPUTYPE", StringType, true),
      StructField("CPUWI", StringType, true),
      StructField("CREFNO2", StringType, true),
      StructField("CREFNO3", StringType, true),
      StructField("CREGCUSTADR1", StringType, true),
      StructField("CREGCUSTADR2", StringType, true),
      StructField("CREGCUSTADR3", StringType, true),
      StructField("CREGCUSTADRDT", StringType, true),
      StructField("CREGCUSTLAT", StringType, true),
      StructField("CREGCUSTLON", StringType, true),
      StructField("CREGCUSTNAME", StringType, true),
      StructField("CREGCUSTPIN", StringType, true),
      StructField("CREGCUSTTEL", StringType, true),
      StructField("CREGTCHG", StringType, true),
      StructField("CREVPU", StringType, true),
      StructField("CRFDCOMPNM", StringType, true),
      StructField("CRTOADR1", StringType, true),
      StructField("CRTOADR2", StringType, true),
      StructField("CRTOADR3", StringType, true),
      StructField("CRTOADRDT", StringType, true),
      StructField("CRTOCONTNM", StringType, true),
      StructField("CRTOIMDTLY", StringType, true),
      StructField("CRTOLAT", StringType, true),
      StructField("CRTOLON", StringType, true),
      StructField("CRTOMOB", StringType, true),
      StructField("CRTOPIN", StringType, true),
      StructField("CRTOTEL", StringType, true),
      StructField("CSENDER", StringType, true),
      StructField("CSPLINST", StringType, true),
      StructField("CSTATCHG", StringType, true),
      StructField("CSTATECODE", StringType, true),
      StructField("CSUBCODE", StringType, true),
      StructField("CTRNCODE", StringType, true),
      StructField("DBATCHDT", StringType, true),
      StructField("DCUSTEDD", StringType, true),
      StructField("DCUSTPUDT", StringType, true),
      StructField("DDOCDATE", StringType, true),
      StructField("DDWNLDDATE", StringType, true),
      StructField("DEPTDTDLV", StringType, true),
      StructField("DFLIGHTDT", StringType, true),
      StructField("DINVDATE", StringType, true),
      StructField("DPUDATE", StringType, true),
      StructField("DSHIPDATE", StringType, true),
      StructField("DUPLDATE", StringType, true),
      StructField("DVALIDUPTO", StringType, true),
      StructField("NACTWGT", StringType, true),
      StructField("NADDISRCHG", StringType, true),
      StructField("NADDOSRCHG", StringType, true),
      StructField("NAMOUNT", StringType, true),
      StructField("NAMT", StringType, true),
      StructField("NASSDVALUE", StringType, true),
      StructField("NAWBFEE", StringType, true),
      StructField("NCARTCHG", StringType, true),
      StructField("NCDUTYPC", StringType, true),
      StructField("NCHGCOLCT", StringType, true),
      StructField("NCHRGWT", StringType, true),
      StructField("NCOLAMT", StringType, true),
      StructField("NCOMVAL", StringType, true),
      StructField("NCSHMEMNO", StringType, true),
      StructField("NDCCHRG", StringType, true),
      StructField("NDCLRDVAL", StringType, true),
      StructField("NDEFERREDDELIVERYDAYS", StringType, true),
      StructField("NDIMB", StringType, true),
      StructField("NDIMH", StringType, true),
      StructField("NDIML", StringType, true),
      StructField("NDIWT", StringType, true),
      StructField("NDOCCHRG", StringType, true),
      StructField("NDODAMT", StringType, true),
      StructField("NFODCHRG", StringType, true),
      StructField("NFREIGHT", StringType, true),
      StructField("NFSAMT", StringType, true),
      StructField("NITEMCNT", StringType, true),
      StructField("NMISCCHG1", StringType, true),
      StructField("NMISCCHG2", StringType, true),
      StructField("NOCTROI", StringType, true),
      StructField("NODACHRG", StringType, true),
      StructField("NOTHCHRGS", StringType, true),
      StructField("NPAYCASH", StringType, true),
      StructField("NPCS", StringType, true),
      StructField("NPUTMSLOT", StringType, true),
      StructField("NREGTCHG", StringType, true),
      StructField("NRISKHCHGS", StringType, true),
      StructField("NSLABWGT", StringType, true),
      StructField("NSTATCHG", StringType, true),
      StructField("NTOKENNO", StringType, true),
      StructField("NVALCHGS", StringType, true),
      StructField("NWEIGHT", StringType, true),
      StructField("op_ts", StringType, true),
      StructField("load_ts", StringType, true),
      StructField("op_flag", StringType, true)))
	  
	  val shipclt_Schema = shipcltSchema
		//val shipclt_Schema = sc.broadcast(shipcltSchema)
    return shipclt_Schema
  }
  def getEligibleTrackSchema(sc:SparkContext): StructType = {
    val eligibleTrack_schema = StructType(
		List(
		StructField("cawbno", StringType, true),
		StructField("cstatgroup", StringType, true),
		StructField("cclosure", StringType, true),
		StructField("dntwrkdt", StringType, true),
		StructField("cstatcode", StringType, true),
		StructField("cprodcode", StringType, true),
		StructField("dorgindt", StringType, true),
		StructField("corginloc", StringType, true),
		StructField("cntwrkloc", StringType, true),
		StructField("doutscndt", StringType, true),
		StructField("dcurstat", StringType, true),
		StructField("ccurstattime", StringType, true),
		StructField("ccurstat", StringType, true),
		StructField("ccurstatloc", StringType, true),
		StructField("dcurscn", StringType, true),
		StructField("ccurscntime", StringType, true),
		StructField("ccurscn", StringType, true),
		StructField("ccurscnloc", StringType, true),
		StructField("ccurstatemp", StringType, true),
		StructField("cstatstr", StringType, true),
		StructField("cnprodcode", StringType, true),
		StructField("cnsubprdcd", StringType, true),
		StructField("cnpacktype", StringType, true),
		StructField("chubdept", StringType, true),
		StructField("dinscandt", StringType, true),
		StructField("doutscndt1", StringType, true),
		StructField("dntwrkdt1", StringType, true),
		StructField("cntwrkloc1", StringType, true),
		StructField("dntwrkdt2", StringType, true),
		StructField("coutscnloc1", StringType, true),
		StructField("cntwrkloc2", StringType, true),
		StructField("cloadloc", StringType, true),
		StructField("dloaddt", StringType, true),
		StructField("coutscanemp", StringType, true),
		StructField("cinscanloc", StringType, true),
		StructField("coutscnloc", StringType, true),
		StructField("cstattype", StringType, true),
		StructField("cloccode", StringType, true),
		StructField("dstatdate", StringType, true),
		StructField("cstattime", StringType, true),
		StructField("cemplcode", StringType, true),
		StructField("pod_journey", StringType, true),
		StructField("cactdelloc", StringType, true),
		StructField("cnmloccode", StringType, true),
		StructField("dpudate", StringType, true),
		StructField("ddstindt", StringType, true),
		StructField("cdstinloc", StringType, true),
		StructField("cndlvstr", StringType, true),
		StructField("dkpi1", StringType, true),
		StructField("ckpi1", StringType, true),
		StructField("ckpi11", StringType, true),
		StructField("dkpi2", StringType, true),
		StructField("ckpi13", StringType, true),
		StructField("ckpi3", StringType, true),
		StructField("dkpi3", StringType, true),
		StructField("load_ts", TimestampType, true)))
				
		val et_schema=eligibleTrack_schema
		//val et_schema= sc.broadcast(eligibleTrack_schema)
    return et_schema
  }

  def getShipmentSchema(sc:SparkContext): StructType = {
    val shipmentSchema = StructType(
    List(
      StructField("nawbid", StringType, true),
      StructField("cawbno", StringType, true),
      StructField("cbatchno", StringType, true),
      StructField("cprodcode", StringType, true),
      StructField("corgarea", StringType, true),
      StructField("corgscrcd", StringType, true),
      StructField("cmawbno", StringType, true),
      StructField("cmloccode", StringType, true),
      StructField("cdstarea", StringType, true),
      StructField("cdstscrcd", StringType, true),
      StructField("cmode", StringType, true),
      StructField("cprodtype", StringType, true),
      StructField("ctrncode", StringType, true),
      StructField("cfoccode", StringType, true),
      StructField("bpriority", StringType, true),
      StructField("ccustcode", StringType, true),
      StructField("csender", StringType, true),
      StructField("ccneecode", StringType, true),
      StructField("cattention", StringType, true),
      StructField("npcs", StringType, true),
      StructField("bvolwt", StringType, true),
      StructField("nweight", StringType, true),
      StructField("nactwgt", StringType, true),
      StructField("ccmdtycode", StringType, true),
      StructField("ntokenno", StringType, true),
      StructField("ncshmemno", StringType, true),
      StructField("namt", StringType, true),
      StructField("cbillno", StringType, true),
      StructField("bduty", StringType, true),
      StructField("bbillcnee", StringType, true),
      StructField("cbillcac", StringType, true),
      StructField("cpacktype", StringType, true),
      StructField("dpudate", StringType, true),
      StructField("cputime", StringType, true),
      StructField("cpuemplcd", StringType, true),
      StructField("deptdtdlv", StringType, true),
      StructField("coda", StringType, true),
      StructField("cflightno", StringType, true),
      StructField("dflightdt", StringType, true),
      StructField("ckgpound", StringType, true),
      StructField("cadecode", StringType, true),
      StructField("cstattype", StringType, true),
      StructField("cstatcode", StringType, true),
      StructField("dstatdate", StringType, true),
      StructField("cstattime", StringType, true),
      StructField("cemplcode", StringType, true),
      StructField("blinked", StringType, true),
      StructField("crecdby", StringType, true),
      StructField("crelation", StringType, true),
      StructField("dpodedate", StringType, true),
      StructField("cpodetime", StringType, true),
      StructField("cpdecode", StringType, true),
      StructField("bedptrnx", StringType, true),
      StructField("bcrcrdref", StringType, true),
      StructField("bcrcrdpay", StringType, true),
      StructField("bsumrisd", StringType, true),
      StructField("dshipdate", StringType, true),
      StructField("cpuwi", StringType, true),
      StructField("cpromocode", StringType, true),
      StructField("csplinst", StringType, true),
      StructField("dbatchdt", StringType, true),
      StructField("biatadtl", StringType, true),
      StructField("cbtparea", StringType, true),
      StructField("cbtpcode", StringType, true),
      StructField("csubcode", StringType, true),
      StructField("cgsacode", StringType, true),
      StructField("dpodupdt", StringType, true),
      StructField("cintlinb", StringType, true),
      StructField("crevpu", StringType, true),
      StructField("cpreftm", StringType, true),
      StructField("cpscode", StringType, true),
      StructField("cfrdawbno", StringType, true),
      StructField("crfdcompnm", StringType, true),
      StructField("crefno2", StringType, true),
      StructField("crefno3", StringType, true),
      StructField("cpumode", StringType, true),
      StructField("cputype", StringType, true),
      StructField("nitemcnt", StringType, true),
      StructField("bpartialpu", StringType, true),
      StructField("npaycash", StringType, true),
      StructField("nputmslot", StringType, true),
      StructField("cmanifstno", StringType, true),
      StructField("coffcltime", StringType, true),
      StructField("ndeferdays", StringType, true),
      StructField("cisddn", StringType, true),
      StructField("cactdelloc", StringType, true),
      StructField("cgstno", StringType, true),
      StructField("DCUSTEDD", StringType, true),
      StructField("CEXCHAWB", StringType, true),
      StructField("DCUSTPUDT", StringType, true),
      StructField("CCUSTPUTM", StringType, true),
      StructField("CAVAILTIME", StringType, true),
      StructField("CAVAILDAYS", StringType, true),
      StructField("dawbupdt", StringType, true),
      StructField("cloccode", StringType, true),
      StructField("nfsamt", StringType, true),
      StructField("ncafamt", StringType, true),
      StructField("nbaseamt", StringType, true),
      StructField("ccrcrdref", StringType, true),
      StructField("op_ts", StringType, true)))
		
		val shipment_Schema = shipmentSchema
		//val shipment_Schema = sc.broadcast(shipmentSchema)
    return shipment_Schema
  }

  def getnotconnectmmfSchema(sc:SparkContext): StructType = {
    val notconnectmmfSchema = StructType(
		List(StructField("CREGION", StringType, true),
		StructField("CAWBNO", StringType, true),
		StructField("DINSCANDT", StringType, true),
		StructField("CORGINLOC", StringType, true),
		StructField("CPRODCODE", StringType, true),
		StructField("CNPRODCODE", StringType, true),
		StructField("CNSUBPRDCD", StringType, true),
		StructField("CNPACKTYPE", StringType, true),
		StructField("CCURSTAT", StringType, true),
		StructField("DCURSTAT", StringType, true),
		StructField("CCURSTATTIME", StringType, true),
		StructField("CCURSTATLOC", StringType, true),
		StructField("CSTATDESC", StringType, true),
		StructField("DPROCDT", StringType, true),
		StructField("CCURSCN", StringType, true),
		StructField("CSTATCODE", StringType, true),
		StructField("CCURSCNLOC", StringType, true),
		StructField("DCURSCN", StringType, true),
		StructField("CCURSCNTIME", StringType, true),
		StructField("CAREA", StringType, true),
		StructField("CCUSTCODE", StringType, true),
		StructField("CCOMPGRP", StringType, true),
		StructField("CSTR", StringType, true),
		StructField("CPULOC", StringType, true),
		StructField("CPUCUTOFF", StringType, true),
		StructField("CDELLOC", StringType, true),
		StructField("CDELCUTOFF", StringType, true),
		StructField("CORGHUB", StringType, true),
		StructField("CDSTHUB", StringType, true),
		StructField("CSERVICE", StringType, true),
		StructField("PCPRODCODE", StringType, true),
		StructField("PCMODE", StringType, true),
		StructField("PCPACKTYPE", StringType, true),
		StructField("PCORGSCRCD", StringType, true),
		StructField("PCDSTSCRCD", StringType, true),
		StructField("CDPULOC", StringType, true),
		StructField("CDPUCUTOFF", StringType, true),
		StructField("CDDELLOC", StringType, true),
		StructField("CDDELCUTOFF", StringType, true),
		StructField("CDORGHUB", StringType, true),
		StructField("CDDSTHUB", StringType, true),
		StructField("CDSERVICE", StringType, true),
		StructField("COFFFLG", StringType, true),
		StructField("PCMLOCCODE", StringType, true),
		StructField("DNTWRKDT", StringType, true),
		StructField("CCPU", StringType, true),
		StructField("CCPUCUTOFF", StringType, true),
		StructField("PCORGAREA", StringType, true),
		StructField("PCCUSTCODE", StringType, true),
		StructField("PCLOADBUFF", StringType, true),
		StructField("PCEDT", StringType, true),
		StructField("CNFSFLG", StringType, true),
		StructField("CROWNUM", LongType, true),
		StructField("CPROCFLAG", StringType, true),
		StructField("DFLD", StringType, true),
		StructField("CFLDLOC", StringType, true),
		StructField("DINDT", StringType, true),
		StructField("CINLOC", StringType, true),
		StructField("CNTWRKLOC", StringType, true),
		StructField("CSTATSTR", StringType, true),
		StructField("DCPUIN", StringType, true),
		StructField("CCPUINLOC", StringType, true),
		StructField("DCPUOS", StringType, true),
		StructField("CCPUPOSLOC", StringType, true),
		StructField("DHUBIN", StringType, true),
		StructField("CHUBINLOC", StringType, true),
		StructField("DHUBOS", StringType, true),
		StructField("CHUBOSLOC", StringType, true),
		StructField("DNTWRKDT1", StringType, true),
		StructField("CNTWRKLOC1", StringType, true),
		StructField("DNTWRKDT2", StringType, true),
		StructField("CNTWRKLOC2", StringType, true),
		StructField("CHUBDEPT", StringType, true),
		StructField("CPURTCD", StringType, true),
		StructField("CPURTNAME", StringType, true),
		StructField("CPUEMPLCD", StringType, true),
		StructField("CLOCTYPE", StringType, true),
		StructField("CSUBLOC", StringType, true),
		StructField("CCURSCNEMP", StringType, true),
		StructField("CCURSTATEMP", StringType, true),
		StructField("CSCDINSCAN", StringType, true),
		StructField("CSCDOUTSCAN", StringType, true),
		StructField("CSCDACTION", StringType, true),
		StructField("CSCDTRANSIT", StringType, true),
		StructField("CCPUINSCAN", StringType, true),
		StructField("CCPUOUTSCAN", StringType, true),
		StructField("CCPUACTION", StringType, true),
		StructField("CCPUTRANSIT", StringType, true),
		StructField("CHUBINSCAN", StringType, true),
		StructField("CHUBOUTSCAN", StringType, true),
		StructField("CHUBACTION", StringType, true),
		StructField("CPRVLEFT", StringType, true),
		StructField("CREJECT", StringType, true),
		StructField("CFLD", StringType, true),
		StructField("DCHKCUTOFF", StringType, true),
		StructField("DOUTSCNDT", StringType, true),
		StructField("CSTATGROUP", StringType, true),
		StructField("CUSTDATA", StringType, true),
		StructField("CHUBNOTREACHED", StringType, true),
		StructField("CHORGHUBSTR", StringType, true),
		StructField("DROLLINSCANDT", StringType, true),
		StructField("CROLLINSCANLOC", StringType, true),
		StructField("DLOADDT", StringType, true),
		StructField("CLOADLOC", StringType, true),
		StructField("DDSTINDT", StringType, true),
		StructField("CDSTINLOC", StringType, true),
		StructField("CNDLVSTR", StringType, true),
		StructField("DNOTINHUB", StringType, true),
		StructField("CNOTINHUBLOC", StringType, true),
		StructField("CNOTINHUB", StringType, true),
		StructField("CDST", StringType, true),
		StructField("CFULLROUTESTR", StringType, true),
		StructField("DEPTDTDLV", StringType, true),
		StructField("CINSCANSTR", StringType, true),
		StructField("DPUDATE", StringType, true),
		StructField("CPUTIME", StringType, true),
		StructField("DOUTSCNDT1", StringType, true),
		StructField("DOUTSCNLOC", StringType, true),
		StructField("CRELATION", StringType, true),
		StructField("CCRCRDREF", StringType, true),
		StructField("CACTDELLOC", StringType, true),
		StructField("CF1", StringType, true),
		StructField("CF2", StringType, true),
		StructField("CF3", StringType, true),
		StructField("CF4", StringType, true),
		StructField("CF5", StringType, true),
		StructField("CF6", StringType, true),
		StructField("CF7", StringType, true),
		StructField("CF8", StringType, true),
		StructField("CF9", StringType, true),
		StructField("CF10", StringType, true),
		StructField("CF11", StringType, true),
		StructField("CF12", StringType, true),
		StructField("CF13", StringType, true),
		StructField("CF14", StringType, true),
		StructField("CF15", StringType, true),
		StructField("CF16", StringType, true),
		StructField("CF17", StringType, true),
		StructField("CF18", StringType, true),
		StructField("CF19", StringType, true),
		StructField("CF20", StringType, true),
		StructField("CF21", StringType, true),
		StructField("CF22", StringType, true),
		StructField("CF23", StringType, true),
		StructField("CF24", StringType, true),
		StructField("CF25", StringType, true),
		StructField("NWEIGHT", StringType, true),
		StructField("CD1", StringType, true),
		StructField("CD2", StringType, true),
		StructField("CD3", StringType, true),
		StructField("CD4", StringType, true),
		StructField("CD5", StringType, true),
		StructField("CD6", StringType, true),
		StructField("CD7", StringType, true),
		StructField("CD8", StringType, true),
		StructField("CD9", StringType, true),
		StructField("CD10", StringType, true),
		StructField("CD11", StringType, true),
		StructField("CD12", StringType, true),
		StructField("CD13", StringType, true),
		StructField("CD14", StringType, true),
		StructField("CD15", StringType, true),
		StructField("COUTSCNEMP", StringType, true),
		StructField("CDLVEMP", StringType, true)));
		
		val notconnect_schema = notconnectmmfSchema
		//val notconnect_schema = sc.broadcast(notconnectmmfSchema)
    return notconnect_schema;
  }
}